version: "3"
services:
  mysql:
    build: ./mysql/
    image: mysql:8-debian
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_HOST: ${DB_HOST}
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/csv:/csv_temps 
    - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  backend:
    build: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/src
    tty: true
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
    command: flask run -h 0.0.0.0
    links:
      - mysql